---
- name:  Application Down - Rememdiation play
  hosts: all
  gather_facts: false
  tasks:
    - name: Application Status
      debug:
        msg: "service down"

    - name: "Restart Application Service"
      service:
        name: httpd
        state: restarted

