---
- name: Site Down
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - debug:
        msg: "Website is down!"

    - name: Launch a workflow
      workflow_launch:
        workflow_template: "WF_restart_application"
        controller_host: https://10.76.107.98
        controller_username: admin
        controller_password: admin
        validate_certs: false
