---
- name: Application Service is Down - Rememdiation Play 
  hosts: 10.76.107.100
  gather_facts: false
  connection: local
  collections:
    - ansible.controller

  tasks:
    - name: Application Service Status 
      debug:
        msg: "Application Service is down!"

    - name: Application Down => Triggering Remediation Workflow
      workflow_launch:
        workflow_template: "WF_restart_application"
        controller_host: https://10.76.107.98
        controller_username: admin
        controller_password: admin
        validate_certs: false
