---
- name: Site status
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - debug:
        msg: "Website is back up!"

    - name: "Status of apache webserver"
      service:
        name: httpd
        state: reloaded
