---
- name: Service Status Play
  hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: "Status of apache webserver"
      ansible.builtin.systemd:
        name: httpd
      register: application_service_status

    - name: Application Status
      debug:
        msg: "Application Service Status => {{ application_service_status.status.ActiveState }}"

