---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
     - ansible.eda.demo:
        file_name: "/etc/motd"
        delay: 5

  rules:
    ## Define the conditions we are looking for
    - name: File exists
      condition: event.demo.status == "exists"
    ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: file-exists.yml

    - name: File missing
      condition: event.demo.status == "missing"
    ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: file-missing.yml
